- name: Install Nginx
  apt:
    name: nginx
    state: present
  

- name: Nginx configuration
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/nodejs
  notify : 
    - Reload Nginx